services:

  worldlineop.sdk.client.factory:
    class: 'WorldlineOP\PrestaShop\Sdk\ClientFactory'
    public: true
    arguments:
      - '@worldlineop.sdk.communicator'
      - '@worldlineop.settings'

  worldlineop.sdk.client:
    class: 'WorldlineOP\PrestaShop\Sdk\ClientFactory'
    public: true
    arguments:
      - '@worldlineop.sdk.communicator'
      - '@worldlineop.settings'
    factory: ['@worldlineop.sdk.client.factory', 'getMerchant']

  worldlineop.sdk.connection:
    class: 'OnlinePayments\Sdk\DefaultConnection'
    public: true

  worldlineop.sdk.communicator_configuration.factory:
    class: 'WorldlineOP\PrestaShop\Sdk\CommunicatorConfigurationFactory'
    public: true
    arguments:
      - '@worldlineop.settings'
      - '@worldlineop.module'

  worldlineop.sdk.communicator:
    class: 'OnlinePayments\Sdk\Communicator'
    public: true
    arguments:
      - '@worldlineop.sdk.connection'
      - '@=service("worldlineop.sdk.communicator_configuration.factory").getInstance()'
