<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzsoCK3\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzsoCK3/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFzsoCK3.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFzsoCK3\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFzsoCK3\appAppKernelProdContainer([
    'container.build_hash' => 'FzsoCK3',
    'container.build_id' => 'e0058635',
    'container.build_time' => 1702376026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzsoCK3');
