<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9RmVPZU\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9RmVPZU/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container9RmVPZU.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container9RmVPZU\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container9RmVPZU\appAppKernelProdContainer([
    'container.build_hash' => '9RmVPZU',
    'container.build_id' => 'a67b1030',
    'container.build_time' => 1704386259,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9RmVPZU');
