<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqcCGJpYQaAtRwY3FWOtQ'."\n".'g30H8uwLXLU5ZeH87AfPh1hgfjk4IEKjnpR5EGpcJdiozGFg7R9tbJ56GDoRmai3'."\n".'djW094W6JdI568uYluDIiI2FhKHXfNhR8D8otvG16nxr6m7TanM3fgvQgeZrmvNG'."\n".'HVSnExiomrkbdk5baCJWpWbPjIEpS09jbfsJdkfBkHtJb6xT3SgyTY5fjJJJ/T0c'."\n".'vcUOJeT9xwkI7meAJWpDN8A02hrCXsn1J9HXzW+vR3MncoE1vUkOVG0aGUtgi13X'."\n".'m1oavcw75PqTcUeqinqRtyMHy2DP4+nBoe6Z4fZuXclxfqZd5nvic2IdFfYiWlcn'."\n".'KQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
