<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXs2t6Cp\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXs2t6Cp/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXs2t6Cp.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXs2t6Cp\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerXs2t6Cp\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Xs2t6Cp',
    'container.build_id' => 'b671e039',
    'container.build_time' => 1695375951,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXs2t6Cp');
