<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQs5kW6\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQs5kW6/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQs5kW6.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQs5kW6\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerSQs5kW6\appAppKernelDevDebugContainer([
    'container.build_hash' => 'SQs5kW6',
    'container.build_id' => '9d825e0f',
    'container.build_time' => 1702382881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQs5kW6');
