<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhJx5KJ\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhJx5KJ/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFhJx5KJ.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFhJx5KJ\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerFhJx5KJ\appAppKernelDevDebugContainer([
    'container.build_hash' => 'FhJx5KJ',
    'container.build_id' => '3f6cf279',
    'container.build_time' => 1695378930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhJx5KJ');
